import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

/**
 * Application Entry Point
 *
 * Modern React 18+ rendering with:
 * - StrictMode for development checks
 * - Concurrent rendering
 * - Service worker registration (PWA)
 */

/**
 * Service Worker Registration
 *
 * Registers the PWA service worker for offline functionality
 * Generated automatically by vite-plugin-pwa
 */
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    // The service worker file is generated by vite-plugin-pwa
    // In production, this will be /sw.js
    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then(registration => {
        console.log('Service Worker registered:', registration.scope);

        // Check for updates on load
        registration.update();
      })
      .catch(error => {
        console.log('Service Worker registration failed:', error);
      });
  });
}

/**
 * React 18 Root API
 *
 * createRoot enables concurrent features:
 * - Automatic batching
 * - Transitions
 * - Suspense improvements
 */
const rootElement = document.getElementById('root');

if (!rootElement) {
  throw new Error('Failed to find root element');
}

const root = createRoot(rootElement);

root.render(
  <StrictMode>
    <App />
  </StrictMode>
);

/**
 * Development-only hot module replacement
 *
 * Preserves state during development
 * Automatically enabled by Vite
 */
if (import.meta.hot) {
  import.meta.hot.accept();
}
